### ISSUE TITLE
Slicing error on Windows 7  - output directory

### ISSUE THREAD

**Issue by tyeeman** [Kagami/mpv_slicing#1]
I'm getting this error on Win 7 

```
[slicing] Lua error: G:/mpv2/portable_config/scripts/slicing.lua:84: bad argument #2 to '
gsub' (string/function/table expected)
```
I think it's due to the tilde character not recognized as a home directory or something like that. What should I change to make it work on a Windows PC so the output path is recognized? I would like mpv to write to it's own directory if I could.

**Comment by zonteck** [comment]
You can change 'os.getenv("HOME")' to a path (.e.g, "a"), like this:
`o.target_dir:gsub("~", "a:"),`

Also in function get_outname() I added this before the return (since ":" shouldn't be in filenames):
`name = name:gsub(":", "-")`

**Comment by tyeeman** [comment]
I did what you said but I'm still getting the same error. Here is what I did - 

```
function cut(shift, endpos)
    local cmd = trim(o.command_template:gsub("%s+", " "))
    local inpath = escape(utils.join_path(
        utils.getcwd(),
        mp.get_property("stream-path")))
    -- TODO: Windows?
    local outpath = escape(string.format("%s/%s",
        o.target_dir:gsub("~", os.getenv("r:")),
        get_outname(shift, endpos)))
```
I see above you had a note about --TODO:Windows? Just wondering if that's got anything to do with it. 

Here is the error I get - 

```
[slicing]
[slicing] stack traceback:
[slicing]       G:/mpv2/portable_config/scripts/slicing.lua:85: in function 'cut'
[slicing]       G:/mpv2/portable_config/scripts/slicing.lua:123: in function 'fn'
[slicing]       mp.defaults:202: in function 'fn'
[slicing]       mp.defaults:60: in function 'handler'
[slicing]       mp.defaults:339: in function 'handler'
[slicing]       mp.defaults:458: in function 'call_event_handlers'
[slicing]       mp.defaults:495: in function 'dispatch_events'
[slicing]       mp.defaults:451: in function <mp.defaults:450>
[slicing]       [C]: at 0x013fd02030
[slicing]       [C]: at 0x013fd01630
[slicing] Lua error: G:/mpv2/portable_config/scripts/slicing.lua:85: bad argument #2 to '
gsub' (string/function/table expected)
```

**Comment by tyeeman** [comment]
Update - I changed "HOME" to a Windows environment variable - "windir". It now is getting closer to working. Here is the error now - looks like it's only the formatting of the file name for ffmpeg to write that is the problem, front slash vs backslash??
```
[slicing] ffmpeg -v warning -y -stats -ss 6.507 -i 'V:\\Movies_mkv\\Survivor S35\\survivor.s35e01.72
0p.hdtv.x264-bajskorv.mkv' -t 5.172 -c:v rawvideo -c:a pcm_s16le  -vf format=yuv444p16,scale=in_colo
r_matrix=bt709,format=bgr24  'C:\\Windows/survivor.s35e01.720p.hdtv.x264-bajskorv.00:00:6.507-00:00:
11.679.avi'
'V:\\Movies_mkv\\Survivor: Invalid argument♪◙♪AV: 00:00:11 / 00:42:44 (0%) A-V:  0.000♪♪.000♪♪.000♪♪
```

**Comment by tyeeman** [comment]
OK, got it working. Did the following - 

Change 'os.getenv("HOME")' to a windows env. path (.e.g, "windir"), like this:
o.target_dir:gsub("~", "windir"), in lines 85 and 39.

Also in function get_outname() added this before the return (since ":" shouldn't be in filenames):
name = name:gsub(":", "-")

In line 17, command template, replace ' with " around $in and $out.$ext like this
"$in" and "$out.$ext"

I guess I can change the ffmpeg command template to anything I want, yes? Like saving in libx264?

**Comment by Kagami** [comment]
Thank you for feedback. Applied fixes.

>I guess I can change the ffmpeg command template to anything I want, yes? Like saving in libx264?

Yes, you can change any value specified in `local o = ...` dict using [mpv configuration mechanism](https://mpv.io/manual/master/#configuration).
