### ISSUE TITLE
Slices overwrite each other

### ISSUE THREAD

**Issue by himanshuxd** [Kagami/mpv_slicing#6]
This script is just great and gets the job done for most people but if I cut slices of the same video, ffmpeg due to the `-y` flag overwrites the previous slice and therefore only the last slice is saved. To overcome this, a counter variable can be used imo. 

Update : It seems Windows doesn't support filenames with ':' character and editing the out file name to not reflect time stamps caused this issue.

**Comment by Mono-Tom** [comment]
Why not just remove the semicolons from the timestamp then? Or replace it with the standard format of timestamps (which is in milliseconds since 1970 I believe)

**Comment by Mono-Tom** [comment]
https://www.lua.org/pil/22.1.html

**Comment by himanshuxd** [comment]
> 
> 
> Why not just remove the semicolons from the timestamp then? Or replace it with the standard format of timestamps (which is in milliseconds since 1970 I believe)

yes I did just that.
